repos:
    - repo: https://github.com/ambv/black
      rev: 22.3.0
      hooks:
          - id: black
            language_version: python3.10
    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: pylint
            language: python
            types: [python]
            args:
                - --rcfile=airbnb_project/lambda_functions/.pylintrc
